version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          package-manager: yarn
          start-command: yarn start
          wait-on: http://localhost:5173
          cypress-command: yarn cypress:run
