version: 2.1
orbs:
  cypress: cypress-io/cypress@3
executors:
  with-chrome:
    resource_class: large
    docker:
      - image: 'cypress/browsers:node16.18.0-chrome90-ff88'
workflows:
  build:
    jobs:
      - cypress/run:
          package-manager: yarn
          requires:
            - cypress/install
          executor: with-chrome
          browser: chrome
          post-steps:
            - run: ls
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/screenshots
