version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          package-manager: yarn
          start-command: 'yarn start'
          cypress-command: 'yarn cypress run --headed --browser chrome'
