version: 2.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Running E2E tests with multiple reporters
          command: yarn start && yarn cypress:run
