version: 2.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node16.16.0-chrome105-ff104-edge
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Starting server
          command: yarn start
          background: true
      - run:
          name: Running Cypress
          command: yarn cypress run --headed --browser firefox
