name: Integration Tests

on: push

jobs:
  integration_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: yarn cypress:run --headed --browser chrome
          start: yarn start
