name: E2E Tests

on:
  push:
    branches: [master]

jobs:
  e2e_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
    env:
      CYPRESS_VITE_API_URL: ${{secrets.CYPRESS_VITE_API_URL}}
